### ISSUE TITLE
Securely stored options a posted to jira comments as plain text

### ISSUE THREAD

**Issue by shoelzle** [rundeck-plugins/jira-notification#7]
Hello,

 I use version 1.0.2 of this plugin to comment job results into jira.
In order to store our passwords encrypted, I added a text option to my rundeck jobs and stored the content in the rundeck key storage.
This prevents my users to access the passwords.

The problem is all options are commented in plain text to jira by this plugin. I don't think this should be the case.

Best Regards
Stefan

**Comment by ahonor** [comment]
@shoelzle I'm not sure I understand correctly. Is the plugin printing the password somewhere?

**Comment by shoelzle** [comment]
@ahonor , exactly, the plugin prints the passwords in plain text in jira ticket comments. I did not expect this to happen, because the option encryption feature rundeck provides is intended to hide passwords from unauthorized users.

**Comment by bthomas1000** [comment]
Thank you Alex.
